### ISSUE TITLE
webデザインの調整

### ISSUE THREAD

**Issue by Ayosan** [MIRAINOHAKOBASU/MainSite01#10]
統一性，機能性，見易さ，センス等・・・

何か思うことある人書き込みお願いします。

**Comment by Ayosan** [comment]
具体的な改善点
・背景写真をふんわり明るく加工
・道に緩急を付加
・バス停のフォルム改善
・トップへ戻るボタン作成
・メニューボタンの下線に影
・ハコバスに影
・作品アイコンのボタンデザイン
・イラスト要素が増えたので、オプション的な物や建物は写真の方がいいかも
・「作品」に説明書きあってもいいかも
・右上タイトルセット（日時など）からピンクを少なく

**Comment by sKawashima** [comment]
> 背景画像
> 道
> 戻るボタン
> メニューボタン下線
> ハコバス影
> オプションは写真
> ピンクを少なく

良いと思います！素材を分けて書き出してもらえればHTMLに導入します！

> バス停フォルム

足元丸くなったのはいい！丸に柱が被ってない状態を見てみたいかな？

> 作品アイコンボタンデザイン

このボタン押したら右に移動しそう…、三角必要かな？

> 作品の説明書き

もし入れるとしたら内容どんな感じになるかな？あんまり想像つかんのよね…
