### ISSUE TITLE
#topViewデザイン修正

### ISSUE THREAD

**Issue by sKawashima** [MIRAINOHAKOBASU/MainSite01#46]
- 学校名・学年・授業名を目立たせる
- 大学ロゴを入れる

**Comment by Ayosan** [comment]
![topview](https://cloud.githubusercontent.com/assets/16602144/12420481/3aa97d84-bf00-11e5-858d-a9389e99cf22.jpg)
トップビューの修正をしました。変更点として、おだしとも協議の結果、文章は横書きが、最も適しているのではないかという結論になりました。

**Comment by sKawashima** [comment]
がっつり変わったな、これはこれで雰囲気嫌いじゃないけど、最初にイメージしたものとはだいぶ変わったな…
- 「ミライノ」に対して「ハコバス」が小さい？気のせい？細かいコトやけど
- これをやってるコースがわからない（デザインだけじゃない！）
- やっぱり日程が見づらいと思う…、[]は()でいいんちゃうか？文字組自体から変えたいけど…
- 結局何を優先して見せるのかがわからん、「ミライノハコバス」→「バスって単なる」→「えっなにこれは」って目が動いた

**Comment by Ayosan** [comment]
・「ミライノ」に対して「ハコバス」が小さい？気のせい？
→　これはサイズ同じだけどフォントの性質上こう見えてて、会場班が調整したものを持っているのでそれをもらおうと思います。

・これをやってるコースがわからない（デザインだけじゃない！）
→情報の削ぎ落としを行った時に消したんだけど、入れたverも作りました（下記）

・結局何を優先して見せるのかがわからん、「ミライノハコバス」→「バスって単なる」→「えっなにこれは」って目が動いた
→個人的には「ミライノハコバス」→「〜作品展示会」→「バスって単なる」で目線が動くと思います。「なにこれは」っていうのも逆にキャッチだと思うけど笑

![topview2](https://cloud.githubusercontent.com/assets/16602144/12422361/fda2c1de-bf09-11e5-8abd-2de681b5cc83.jpg)

**Comment by Ayosan** [comment]
![topview4](https://cloud.githubusercontent.com/assets/16602144/12422785/f0625ff0-bf0b-11e5-8a6e-85dae0283cd3.jpg)
展示会タイトル差し替えました

**Comment by sKawashima** [comment]
・ロゴのフォント→了解です
・先生がコースを主張したいって言ってたので出しました

・目線の動き僕個人だけかもしれやんけど、でかいロゴの直下の情報は全然重要視してなかった
<img width="1187" alt="fda2c1de-bf09-11e5-8abd-2de681b5cc83_jpg__1192x744_" src="https://cloud.githubusercontent.com/assets/9900753/12422748/c48e5230-bf0b-11e5-99a7-4eb96926f7f6.png">
添付は僕なりの目線の遷移で、コースとかの情報すごい後回しで入ってくる印象

**Comment by sKawashima** [comment]
ただ、すごい綺麗にまとまってていいとは思います
最初考えてたものと結構離れるのと、これより下の部分をデザイン変えなくても雰囲気が崩れないかの不安があります

**Comment by Ayosan** [comment]
私はwebサイトは上から下に見ていくものだと思うので、視線が一度上に戻るという人は少ないと思います。

**Comment by sKawashima** [comment]
上から下に見るけど、ロゴの下の文字をわざわざ見ようとは思わないんで、もし下まで見た時「で、これは何？」って考えた時に巻き戻りが発生する可能性を示唆しています

**Comment by sKawashima** [comment]
強く浮き出てるのが「ミライノハコバス」と「バスって単なる」だけ に見えるってことだな

**Comment by sKawashima** [comment]
上から下に見るからこそ、あんまり浮かなくても読ませるために一番上に「情報デザインコース〜」を置きたいと思いました

**Comment by tunakanoisii** [comment]
「発表会」の文字と日付が離れていて、この日付て何なんだっけ？ってなりそう。自分はトップ画面を見た後一旦視線が上に戻る（日付の意味を探しにもう一回サイトを上から見直す）感じになりました…
順番的には発表会が有る→日付はこうです→内容はこうです　じゃないかな。
メニューバーの上にフェイスブックは違和感があるなぁ…

**Comment by tunakanoisii** [comment]
課題作品発表会と日付は近くに置くべきだと思う。今のままだと「この日付って何？」っていう疑問が出てしまうと思いました〜

**Comment by Ayosan** [comment]
ひとつずつ回答します
<img width="1187" alt="c48e5230-bf0b-11e5-99a7-4eb96926f7f6" src="https://cloud.githubusercontent.com/assets/16602144/12424449/933ef5e2-bf13-11e5-8433-e9d146d48d8a.png">
タイトルと「情報デザインコース〜」を変更してみました。タイトルロゴの色の強さから考えて、目線の動きが「タイトル」から入り、近くのものが読みとばれやすいことは変わりないと思いますが、どう思いますか？「ミライノハコバス」を事前に知っている人だからこそ読み飛ばしやすく、知らない人ほど注視するのかなと思うので、この改善に関してはレイアウトの好みの問題かと思います。私は一般的なwebのロゴは左上が自然だと思っていたので、そうしていました。

**Comment by Ayosan** [comment]
![topview5](https://cloud.githubusercontent.com/assets/16602144/12425112/9d2fb106-bf16-11e5-88d7-60bd64584f72.jpg)
画像間違えました

**Comment by Ayosan** [comment]
まずタイトル→作品展示会と読ませるに当たって不自然な目の動きが起こること、強弱における目線の誘導にそれほど違いがないことを言いたいです

**Comment by Ayosan** [comment]
日付に関して
日付の上に「会場：」のように「開催日時」というタグを増やすのはどうでしょうか。

日付はこの展示会に行きたいと思った人が欲しい情報
概要はこの展示会を知る為の情報

なので、情報の優先度は「知る」が先と考えました。

**Comment by Ayosan** [comment]
フェイスブックに関して

違和感のない場所はどこだと思いますか？（これをもとに改善案提示します）

**Comment by Ayosan** [comment]
![topview6](https://cloud.githubusercontent.com/assets/16602144/12426626/fa580304-bf1d-11e5-9283-82ca1ca548d4.jpg
上記をもとに改善しました。

フェイスブックの扱いを新しく提案したいと思い、トップビューから削除しました。
詳しくはナビゲーションのissueに書きます。

**Comment by sKawashima** [comment]
- タイトルと展示会の順番：

> 事前に知っている人だからこそ読み飛ばしやすく

これについては納得です、最初の方でいいかもしれない
で、後からの気付きで申し訳ないんですが、未来大について大して何も知らない人がこれを見た時、「ユーザーセンタードデザイン」が授業名でわからない可能性があると感じました
- 日付に関して

タグを増やすこと自体に反対はないですが、トップに日付くらいは会っていいと思います
時間に関しては下で改めて日付で載せる…と言うのはどうでしょう？

**Comment by Ayosan** [comment]
日付はちゃんとトップビューで見える範囲に入れてます。

**Comment by Ayosan** [comment]
LINEにも書きましたが、文章部分をもう少し詳しくして、未来大生の活動であることや、授業のことを説明する文章を追加してもいいかなと思います。

**Comment by Ayosan** [comment]
![topview7](https://cloud.githubusercontent.com/assets/16602144/12438563/5b6f0488-bf6b-11e5-8cfe-209221ab26a0.jpg)
最新版です（右端を揃えました）

**Comment by sKawashima** [comment]
日時・会場周りがとても見やすくなった印象！

**Comment by Ayosan** [comment]
（確かに揃えただけで、日時・会場周りすっきりしたかも！）

**Comment by Ayosan** [comment]
![topview8](https://cloud.githubusercontent.com/assets/16602144/12440662/4f04cc62-bf81-11e5-80fd-6eb5ae132799.jpg)
日付のところに強弱をつけてみました

**Comment by sKawashima** [comment]
良いと思います
僕的には強いて突っ込むところは無いです

**Comment by Ayosan** [comment]
了解です。素材作っておきます。もえなさんの文章ができたら、差し替えたものを画像で出力してここに載せます。それをもって、とりあえずトップビューデザイン案完成とします
