### ISSUE TITLE
menuアイコンの間に空間ができてしまう問題について

### ISSUE THREAD

**Issue by Ayosan** [MIRAINOHAKOBASU/MainSite01#71]
新しいmenuを作成していますが、
menuボタン同士の間に無駄な空間ができてしまって、
ホバーエフェクトがおかしくなります。

自己解決が難しいので誰か助けてください。
ブランチayo/topviewです。

**Comment by sKawashima** [comment]
解決しました
確認をお願いします
当該commit: 27d671f881268e6d155f5fbbc926acee0c89a2a

**Comment by Ayosan** [comment]
ありがと〜！！！
