### ISSUE TITLE
タイトル変更等

### ISSUE THREAD

**Issue by Ayosan** [MIRAINOHAKOBASU/MainSite01#81]
<未変更>
ほそかわくん「みちくさアプリ」
しょーえい「マイスターのいるバス」
うめにわ「乗客の縁を共有するバス」
10班タイトル「つながる、わかる、周遊号」
りょっけ「良く見える窓」
7班アイコン
かな「細道LVバス」
やまうち「インタラクティブバスカード」
奥野「様々な景色を作る双眼鏡」
トップビューの文章

<すでに変更済み>
2班「インフォメーションバス」
7班「観光客と地元住民の共存」
（村山もタイトル「ハコバスマイカード」に変更しました）

**Comment by sKawashima** [comment]
変更、あよさんに一任していいですか
複数人数が触ると扱いにくそうなので

**Comment by Ayosan** [comment]
はい〜一応混乱防ぐために、変えたもの載せていきます。（大量にあってなきそう笑）

**Comment by sKawashima** [comment]
おだしのやつも要確認らしいです

**Comment by tunakanoisii** [comment]
函館市西部地区を巡るバス「元町・ベイエリア周遊号」を題材に、新しいバスの体験をデザインしました。利用客と周遊号の関わりを調査し、バスを使った新しい観光、または住民目線のバスの活用方法を提案しました。この展示会では、ユーザーを中心に考えてデザインする「ユーザーセンタードデザイン」という授業での提案物を発表します。

トップビューの文章です
